### ISSUE TITLE
error while running esp_collect on single DB

### ISSUE THREAD

**Issue by abdulirfan3** [carlos-sierra/esp_collect#1]
Hi Carlos,

While running "esp_master.sql" i got the below error, does this need to be fixed or okay to ignore ??

SQL> @sql/esp_master.sql
Executing esp_collect_requirements and resources_requirements
Please wait ...
SP2-0310: unable to open file "--skip--sql/esp_collect_requirements_statspack.sql"
SP2-0310: unable to open file "--skip--sql/resources_requirements_statspack.sql"
SQL> !ls -ltr
total 848
drwxr-xr-x 2 oracle dba   4096 Mar 27 11:20 sql
-rwxr-xr-x 1 oracle dba    586 Mar 27 11:20 run_esp_master_solaris.sh
-rwxr-xr-x 1 oracle dba   2050 Mar 27 11:20 run_esp_master_linux.sh
-rwxr-xr-x 1 oracle dba   2110 Mar 27 11:20 run_esp_master_aix.sh
-rwxr-xr-x 1 oracle dba   1963 Mar 27 11:20 run_esp.yml
-rw-r--r-- 1 oracle dba   1168 Mar 27 11:20 readme.txt
-rw-r--r-- 1 oracle dba 723969 May  1 12:55 esp_requirements_awr_usaws910_20160501.csv
-rw-r--r-- 1 oracle dba  80297 May  1 12:55 res_requirements_awr_usaws910_20160501.txt
-rw-r--r-- 1 oracle dba  34184 May  1 12:55 esp_output_usaws910_20160501.zip

SQL> exit

**Comment by carlos-sierra** [comment]
Those errors are expected and safe to ignore. Just be sure always to download latest version.

**Comment by abdulirfan3** [comment]
Okay thank you !!!
